CC = /usr/bin/gcc-9
CFLAGS = -Wall -g -O2 -Werror -std=gnu99

EXECUTABLE = csapp

SRC_DIR = ./src

CODE = 	./src/cpu/mmu.c \
		./src/disk/code.c \
		./src/memory/dram.c \
		./src/memory/instruction.c \
		./src/main.c

.PHONY: csapp
csapp:
	$(CC) $(CFLAGS) -I$(SRC_DIR) $(CODE) -o $(EXECUTABLE)

clean:
	rm -f *.o *~ $(EXECUTABLE)

run:
	./$(EXECUTABLE)